{% set version = "0.6.0" %}

package:
  name: tempita
  version: {{ version }}

source:
  fn: Tempita-{{ version }}dev.tar.gz
  url: https://pypi.io/packages/source/T/Tempita/tempita-{{ version }}.tar.gz
  sha256: 76e15de0137e5011c22949cc15a5161f623fe6a31655751c6d765db6bbac27b6
  patches:
    - except.patch
    - setup.patch

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - tempita

about:
  home: http://pythonpaste.org/tempita/
  license: MIT
  license_file: LICENSE
  summary: A small templating language
  description: |
    tempita is a small templating language. This language implements
    if/elif/else, for/continue/break, expressions, and blocks of Python code.
  doc_url: http://pythonpaste.org/tempita/
  dev_url: https://bitbucket.org/ianb/tempita

extra:
  recipe-maintainers:
    - msarahan
    - jan-janssen
